### ISSUE TITLE
hello，your job is awesome，can you support the dataset link？i can not find

### ISSUE THREAD

**Issue by zhujiesuper** [AyoubOuddah/SAR_River_Segmentation_Pytorch-Unet#1]

**Comment by AyoubOuddah** [comment]
Hello,
Sadly i can't share the dataset without the permission of the owner.
In other hand i can provide the [weights](https://drive.google.com/drive/folders/19DGesIl_dhGX_SaRJEtFOlkH_L76vwXz?usp=sharing).
- OneChannel : trained on VV channel only.
- TwoChannels : trained on VV and VH chennels.
Finally you can download SAR images freely on [Open Access Hub](https://scihub.copernicus.eu/) for the training and testing purposes.

**Comment by zhujiesuper** [comment]
Thank you very much！but whether the data online is same as your dataset ？

**Comment by AyoubOuddah** [comment]
The shared weights where trained using my dataset (approximately 1800 patch of 512px X 512px) for 80 epoch each.

**Comment by zhujiesuper** [comment]
Thank you，but can I use your code train/test the data from Open Access Hub directly?

**Comment by AyoubOuddah** [comment]
you should transform the data into a numpy array with the structure [VV, VH, GT].

**Comment by zhujiesuper** [comment]
thank you！

**Comment by zhujiesuper** [comment]
hello, I can not find the dataset in the web you give me. can you tell me the way how can i get?
